<%@ Page Language="vb" AutoEventWireup="false" CodeBehind="Teacher.aspx.vb" Inherits="DOCS.Teacher" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <link href="Style/teacher.css" rel="stylesheet" />
    <link href="Style/master.css" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="Style/loading.css"/>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css"/> 
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet"/>
    <link href="https://fonts.googleapis.com/css?family=Prosto+One" rel="stylesheet"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script src="Script/teacher.js"></script>

    <title>DOCS | Teachers</title>

    <style>
        .dropdown-content a:hover{
          border-bottom: none;
        }
    </style>

</head>

<body onload="changeHashOnLoad();">
    <header></header>
    <div class="loader"></div>
    <div class="header">
        <a href="Home.aspx"><img src="Images/logo.png" height="70" width="100" style="padding-top:8px;"/></a>
        <span style="cursor:default;">Record Management</span>
    </div>
    
<div class="topnav" id="myTopnav">
  <a onclick="logout()" class="active" style="color:white;"><i class="fas fa-home"></i></a>
  <a onclick="logout()" class="right_login"><i class="fas fa-sign-out-alt"></i>&nbsp;Logout</a>
    <a onclick="printDiv()"><i class="fas fa-print"></i>&nbsp;Print</a>
  <a href="javascript:void(0);" class="icon" onclick="myFunction()">
    <i class="fas fa-bars"></i>
  </a>
</div>
    <div class="responsive_img">
    <form id="form1" runat="server" visible="true"> 

<!-----------------------------DASHBOARD---------------------------------------->
<div class="dashboard" id="dash_board">
    <div class="heading">  <h3>Records</h3>
    </div>
    <div class="drop">
         <asp:DropDownList ID="DropDownList1" runat="server" AutoPostBack="True" OnSelectedIndexChanged="Select_semester" CssClass="drop_list">
             <asp:ListItem Text = "Select Semester" Value = ""></asp:ListItem>
         </asp:DropDownList> 

          <asp:DropDownList ID="DropDownList2" runat="server" AutoPostBack="True" OnSelectedIndexChanged="Select_course" Enabled="false" CssClass="drop_list" >
             <asp:ListItem Text = "Select Subject" Value = ""></asp:ListItem>
         </asp:DropDownList>
        </div>
    <div class="control" id="controls">
         <asp:TextBox ID="txtroll" runat="server" CssClass="drop_list" placeholder="Enter Roll No." autocomplete="off"></asp:TextBox>
         <asp:TextBox ID="txtname" runat="server" CssClass="drop_list" placeholder="Enter Name" autocomplete="off"></asp:TextBox>
         <asp:TextBox ID="txtmarks" runat="server" CssClass="drop_list" placeholder="Enter Marks" autocomplete="off"></asp:TextBox>
         <asp:Button ID="Insert_btn" runat="server" Text="Insert" CssClass="insert_btn" />
    </div>
    <div id="prnt">
    <asp:GridView ID="GridView1" runat="server" CellPadding="4" ForeColor="#333333" GridLines="None" Height="80px" Width="100%" AutoGenerateDeleteButton="true" OnRowDeleting="GridView1_RowDeleting" AutoGenerateEditButton="true" OnRowEditing="GridView1_RowEditing" OnRowUpdating="GridView1_RowUpdating" OnRowCancelingEdit="GridView1_RowCancelingEdit" DataKeyNames="ROLL_NO">
        <AlternatingRowStyle BackColor="White" />
        <EditRowStyle BackColor="#bababa" />
        <FooterStyle BackColor="#1C5E55" Font-Bold="True" ForeColor="White" />
        <HeaderStyle BackColor="#00D98F" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="#666666" ForeColor="White" HorizontalAlign="Center" />
        <RowStyle BackColor="#E3EAEB" HorizontalAlign="Center" />
        <SelectedRowStyle BackColor="#C5BBAF" Font-Bold="True" ForeColor="#333333" />
        <SortedAscendingCellStyle BackColor="#F8FAFA" />
        <SortedAscendingHeaderStyle BackColor="#246B61" />
        <SortedDescendingCellStyle BackColor="#D4DFE1" />
        <SortedDescendingHeaderStyle BackColor="#15524A" />
    </asp:GridView>
</div>  
</div>
<!-----------------------------DASHBOARD---------------------------------------->
</form>
</div>
    <footer style="float:right;padding-right:10px"><i class="far fa-copyright"></i>&nbsp;IngeniousTekki</footer>
</body>
</html>
